excluded:
  - Pods
  - FilmeoUnitTests
  - Templates
  - Filmeo*/*.generated.swift
  - rename.swift
line_length:
 warning: 150
 error: 200
file_length:
  warning: 300
  error: 400
function_body_length:
  warning: 30
  error: 50
function_parameter_count:
  warning: 5
  error: 7
closure_body_length:
  warning: 15
  error: 20
  
opt_in_rules:
- anyobject_protocol
- array_init
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_body_length
- closure_parameter_position
- closure_spacing
- collection_alignment
- colon
- comma
- compiler_protocol_init
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- control_statement
- custom_rules
- deployment_target
- discarded_notification_center_observer
- discouraged_direct_init
- discouraged_object_literal
- duplicate_enum_cases
- duplicate_imports
- dynamic_inline
- empty_collection_literal
- empty_count
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
- empty_string
- empty_xctest_method
- enum_case_associated_values_count
- expiring_todo
- explicit_init
- explicit_self
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_length
- file_name_no_space
- first_where
- flatmap_over_map_reduce
- for_where
- force_cast
- force_try
- force_unwrapping
- function_body_length
- function_parameter_count
- generic_type_name
- identical_operands
- implicit_getter
- implicitly_unwrapped_optional
- inert_defer
- is_disjoint
- joined_default_parameter
- large_tuple
- last_where
- leading_whitespace
- legacy_cggeometry_functions
- legacy_constant
- legacy_constructor
- legacy_hashing
- legacy_multiple
- legacy_nsgeometry_functions
- legacy_random
- let_var_whitespace
- line_length
- lower_acl_than_parent
- mark
- modifier_order
- multiline_function_chains
- multiline_parameters
- multiple_closures_with_trailing_closure
- nimble_operator
- no_fallthrough_only
- no_space_in_method_call
- nslocalizedstring_key
- nslocalizedstring_require_bundle
- nsobject_prefer_isequal
- opening_brace
- operator_usage_whitespace
- operator_whitespace
- optional_enum_case_matching
- orphaned_doc_comment
- overridden_super_call
- override_in_extension
- prefer_self_type_over_type_of_self
- private_action
- private_outlet
- private_over_fileprivate
- private_unit_test
- prohibited_super_call
- protocol_property_accessors_order
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- raw_value_for_camel_cased_codable_enum
- reduce_boolean
- reduce_into
- redundant_discardable_let
- redundant_nil_coalescing
- redundant_objc_attribute
- redundant_optional_initialization
- redundant_set_access_control
- redundant_string_enum_value
- redundant_type_annotation
- redundant_void_return
- required_enum_case
- return_arrow_whitespace
- shorthand_operator
- single_test_class
- sorted_first_last
- statement_position
- static_operator
- strict_fileprivate
- superfluous_disable_command
- switch_case_alignment
- switch_case_on_newline
- syntactic_sugar
- todo
- toggle_bool
- trailing_closure
- trailing_comma
- trailing_newline
- trailing_semicolon
- type_body_length
- unavailable_function
- unneeded_break_in_switch
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- unused_capture_list
- unused_closure_parameter
- unused_control_flow_label
- unused_declaration
- unused_enumerated
- unused_import
- unused_optional_binding
- unused_setter_value
- valid_ibinspectable
- vertical_parameter_alignment
- vertical_parameter_alignment_on_call
- vertical_whitespace
- void_return
- weak_delegate
- xct_specific_matcher
- xctfail_message
- yoda_condition
disabled_rules:
- attributes
- file_header
- explicit_acl
- explicit_top_level_acl
- explicit_type_interface
- no_grouping_extension
- prohibited_interface_builder
- required_deinit
- strong_iboutlet
- trailing_whitespace
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- vertical_whitespace_between_cases
- explicit_enum_raw_value
- conditional_returns_on_newline
- type_contents_order
- discouraged_optional_boolean
- discouraged_optional_collection
- no_extension_access_modifier
- number_separator
- multiline_parameters_brackets
- multiline_arguments_brackets
- multiline_arguments
- identifier_name
- sorted_imports
- cyclomatic_complexity
- pattern_matching_keywords
- convenience_type
- type_name
- object_literal
- prefixed_toplevel_constant
- multiline_literal_brackets
- nimble_operator
- file_types_order
- file_name
- literal_expression_end_indentation
- untyped_error_in_catch
- function_default_parameter_at_end
- notification_center_detachment
- nesting
- missing_docs
- closure_end_indentation
- implicit_return

